name: native_ui
description: NativeUI widgets for Android and iOS
version: 0.0.5
author: Carlos A. Escobar <mrescobarandres@gmail.com>
homepage: https://github.com/carlosjs23/nativeui

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

environment:
  sdk: '>=1.19.0 <3.0.0'